# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_num_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(90, 20, 51, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 21, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 50, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 52, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 107, 51, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 109, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 77, 51, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 78, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 169, 51, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 196, 51, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 197, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 171, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 226, 51, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 139, 51, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 228, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(90, 288, 51, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(90, 407, 51, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 315, 51, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 316, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 378, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 290, 81, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(90, 345, 51, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 258, 51, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 347, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 409, 81, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 377, 51, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 259, 81, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(241, 51, 51, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(161, 53, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(161, 22, 81, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(241, 259, 51, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(241, 108, 51, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(161, 79, 81, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(241, 170, 51, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(241, 197, 51, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(241, 408, 51, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(241, 378, 51, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(161, 141, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(161, 379, 81, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(241, 346, 51, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(241, 140, 51, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(161, 317, 81, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(161, 172, 81, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(241, 316, 51, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(241, 78, 51, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(161, 260, 81, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(241, 289, 51, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(161, 198, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(161, 229, 81, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(161, 348, 81, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(161, 291, 81, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(161, 110, 81, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(241, 227, 51, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(241, 21, 51, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(161, 406, 81, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(310, 349, 81, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(310, 23, 81, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(310, 318, 81, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(390, 171, 51, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(310, 199, 81, 16))
        self.label_32.setObjectName("label_32")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(390, 109, 51, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(390, 141, 51, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(310, 173, 81, 16))
        self.label_33.setObjectName("label_33")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(390, 52, 51, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(390, 22, 51, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_37.setGeometry(QtCore.QRect(390, 260, 51, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_36.setGeometry(QtCore.QRect(390, 228, 51, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(310, 380, 81, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(310, 142, 81, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(390, 79, 51, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(310, 111, 81, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(310, 407, 81, 20))
        self.label_37.setObjectName("label_37")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_41.setGeometry(QtCore.QRect(390, 379, 51, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_40.setGeometry(QtCore.QRect(390, 347, 51, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(310, 261, 81, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(310, 54, 81, 16))
        self.label_39.setObjectName("label_39")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(390, 198, 51, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(310, 230, 81, 16))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(310, 292, 81, 16))
        self.label_41.setObjectName("label_41")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_39.setGeometry(QtCore.QRect(390, 317, 51, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_42.setGeometry(QtCore.QRect(390, 409, 51, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(310, 80, 81, 16))
        self.label_42.setObjectName("label_42")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_38.setGeometry(QtCore.QRect(390, 290, 51, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(460, 23, 81, 16))
        self.label_44.setObjectName("label_44")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_48.setGeometry(QtCore.QRect(540, 171, 51, 20))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_46.setGeometry(QtCore.QRect(540, 109, 51, 20))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_47.setGeometry(QtCore.QRect(540, 141, 51, 20))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(460, 173, 81, 16))
        self.label_47.setObjectName("label_47")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_44.setGeometry(QtCore.QRect(540, 52, 51, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_43.setGeometry(QtCore.QRect(540, 22, 51, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(460, 142, 81, 16))
        self.label_49.setObjectName("label_49")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_45.setGeometry(QtCore.QRect(540, 79, 51, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(460, 111, 81, 16))
        self.label_50.setObjectName("label_50")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(460, 54, 81, 16))
        self.label_53.setObjectName("label_53")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(460, 80, 81, 16))
        self.label_56.setObjectName("label_56")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(464,200, 161, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_2.clicked.connect(self.lineEdit_save_into_csv)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 410, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 410, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(mainWindow.close)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(460, 280, 171, 120))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(460, 250, 171, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(460, 230, 101, 16))
        self.label_43.setObjectName("label_43")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "JLTP-A型塞规数据采集器"))
        self.label.setText(_translate("mainWindow", "1号塞规尺寸："))
        self.label_2.setText(_translate("mainWindow", "2号塞规尺寸："))
        self.label_3.setText(_translate("mainWindow", "4号塞规尺寸："))
        self.label_4.setText(_translate("mainWindow", "3号塞规尺寸："))
        self.label_5.setText(_translate("mainWindow", "7号塞规尺寸："))
        self.label_6.setText(_translate("mainWindow", "6号塞规尺寸："))
        self.label_7.setText(_translate("mainWindow", "8号塞规尺寸："))
        self.label_8.setText(_translate("mainWindow", "5号塞规尺寸："))
        self.label_9.setText(_translate("mainWindow", "11号塞规尺寸："))
        self.label_10.setText(_translate("mainWindow", "13号塞规尺寸："))
        self.label_11.setText(_translate("mainWindow", "10号塞规尺寸："))
        self.label_13.setText(_translate("mainWindow", "12号塞规尺寸："))
        self.label_14.setText(_translate("mainWindow", "14号塞规尺寸："))
        self.label_16.setText(_translate("mainWindow", "9号塞规尺寸："))
        self.label_12.setText(_translate("mainWindow", "16号塞规尺寸："))
        self.label_15.setText(_translate("mainWindow", "15号塞规尺寸："))
        self.label_17.setText(_translate("mainWindow", "17号塞规尺寸："))
        self.label_18.setText(_translate("mainWindow", "19号塞规尺寸："))
        self.label_19.setText(_translate("mainWindow", "27号塞规尺寸："))
        self.label_20.setText(_translate("mainWindow", "25号塞规尺寸："))
        self.label_21.setText(_translate("mainWindow", "20号塞规尺寸："))
        self.label_22.setText(_translate("mainWindow", "23号塞规尺寸："))
        self.label_23.setText(_translate("mainWindow", "21号塞规尺寸："))
        self.label_24.setText(_translate("mainWindow", "22号塞规尺寸："))
        self.label_25.setText(_translate("mainWindow", "26号塞规尺寸："))
        self.label_26.setText(_translate("mainWindow", "24号塞规尺寸："))
        self.label_27.setText(_translate("mainWindow", "18号塞规尺寸："))
        self.label_28.setText(_translate("mainWindow", "28号塞规尺寸："))
        self.label_29.setText(_translate("mainWindow", "40号塞规尺寸："))
        self.label_30.setText(_translate("mainWindow", "29号塞规尺寸："))
        self.label_31.setText(_translate("mainWindow", "39号塞规尺寸："))
        self.label_32.setText(_translate("mainWindow", "35号塞规尺寸："))
        self.label_33.setText(_translate("mainWindow", "34号塞规尺寸："))
        self.label_34.setText(_translate("mainWindow", "41号塞规尺寸："))
        self.label_35.setText(_translate("mainWindow", "33号塞规尺寸："))
        self.label_36.setText(_translate("mainWindow", "32号塞规尺寸："))
        self.label_37.setText(_translate("mainWindow", "42号塞规尺寸："))
        self.label_38.setText(_translate("mainWindow", "37号塞规尺寸："))
        self.label_39.setText(_translate("mainWindow", "30号塞规尺寸："))
        self.label_40.setText(_translate("mainWindow", "36号塞规尺寸："))
        self.label_41.setText(_translate("mainWindow", "38号塞规尺寸："))
        self.label_42.setText(_translate("mainWindow", "31号塞规尺寸："))
        self.label_44.setText(_translate("mainWindow", "43号塞规尺寸："))
        self.label_47.setText(_translate("mainWindow", "48号塞规尺寸："))
        self.label_49.setText(_translate("mainWindow", "47号塞规尺寸："))
        self.label_50.setText(_translate("mainWindow", "46号塞规尺寸："))
        self.label_53.setText(_translate("mainWindow", "44号塞规尺寸："))
        self.label_56.setText(_translate("mainWindow", "45号塞规尺寸："))
        self.pushButton_2.setText(_translate("mainWindow", "保存塞规尺寸"))
        self.pushButton_3.setText(_translate("mainWindow", "启动采集"))
        self.pushButton_4.setText(_translate("mainWindow", "停止采集"))
        self.label_43.setText(_translate("mainWindow", "采集文件命名："))